### ISSUE TITLE
ssh connection error & broker master 重启消失

### ISSUE THREAD

**Issue by zachcr** [sohutv/mqcloud#12]
* 在安装broker的时候偶尔会出现ssh无法连接的情况，需要重试很多次就又可以继续安装了。
* 健康的broker下线，再上线的时候。偶尔会出现broker直接消失的情况。提示已经显示broker启动成功，但是还是消失了。

不确定是否这两个issue有关联？

**Comment by gaoyf** [comment]
1. ssh连接取决于网络状况，如果mqcloud机器和broker机器网络不好可能会出现，建议调大ssh连接超时时间。
2. 下线后，其broker列表是从数据库读的，不会消失，当然需要执行如下操作先将broker关系写入数据库：
![image](https://user-images.githubusercontent.com/10137071/102455906-59ff7100-407b-11eb-8506-4d21d3c31bdf.png)

两者没有关联

**Comment by zachcr** [comment]
注册到NameServer还需要一段时间 半个小时还没进去我们就重新 setup了。没有继续等。半个小时正常吗？

**Comment by gaoyf** [comment]
最多几分钟，如果半个小时，建议发broker日志和mqcloud日志上来看看
