### ISSUE TITLE
同一个consumer group为什么不支持消费多个topic？出于哪些方面的考量？

### ISSUE THREAD

**Issue by Willing-Xyz** [sohutv/mqcloud#15]

**Comment by gaoyf** [comment]
举个例子，假如有两个topic，分别为topic1和topic2。有一个consumerGroup，它同时订阅了topic1和topic2。
那么，无论什么时候，该consumerGroup下的实例必须**完全遵从这个订阅关系，否则将引起消费混乱(丢失或重复消费等)**。
请试想一下如下情况：
1. 某个业务用了该consumerGroup，但是它不需要topic2的消息，这时候该怎么办？
2. 由于业务扩展，新增了一个topc3，consumerGroup需要也订阅topic3，那么新旧业务订阅关系在上线的过程中如何保持一致？
3. 由于业务扩展，新增了一个topc3，consumerGroup所属的不同业务，有的需要topic3，有的不需要topic3，怎么办？

种种这些情况是无法用程序检测的，需要业务方熟悉rocketmq这种特性！
业务方很有可能混用同一个consumerGroup导致线上故障！
而以上的种种情形完全能够通过一个consumerGroup只对应一个topic来解决，而增加consumerGroup不会对broker带来任何性能上的问题，何乐而不为呢！

**Comment by Willing-Xyz** [comment]
> 举个例子，假如有两个topic，分别为topic1和topic2。有一个consumerGroup，它同时订阅了topic1和topic2。
> 那么，无论什么时候，该consumerGroup下的实例必须**完全遵从这个订阅关系，否则将引起消费混乱(丢失或重复消费等)**。
> 请试想一下如下情况：
> 
> 1. 某个业务用了该consumerGroup，但是它不需要topic2的消息，这时候该怎么办？
> 2. 由于业务扩展，新增了一个topc3，consumerGroup需要也订阅topic3，那么新旧业务订阅关系在上线的过程中如何保持一致？
> 3. 由于业务扩展，新增了一个topc3，consumerGroup所属的不同业务，有的需要topic3，有的不需要topic3，怎么办？
> 
> 种种这些情况是无法用程序检测的，需要业务方熟悉rocketmq这种特性！
> 业务方很有可能混用同一个consumerGroup导致线上故障！
> 而以上的种种情形完全能够通过一个consumerGroup只对应一个topic来解决，而增加consumerGroup不会对broker带来任何性能上的问题，何乐而不为呢！

感谢回复。 
确实可以解决多个topic的问题，但是上面列举的三种情况，即使是单个topic，不同的consumer还是有可能订阅不同的tag，这一样会导致不一致。
所以，其实一个consumer group对应一个topic并没有彻底解决问题，只是降低了风险。

**Comment by gaoyf** [comment]
关于tag参考mqcloud的[wiki](https://github.com/sohutv/mqcloud/blob/master/mq-cloud/src/main/resources/static/wiki/userGuide/faq.md#user-content-8-%E8%83%BD%E5%90%A6%E4%BD%BF%E7%94%A8tags)。
![image](https://user-images.githubusercontent.com/10137071/113845403-0fd80200-97c8-11eb-8400-5ee3e4372696.png)
