### ISSUE TITLE
对多集群的同名topic的支持

### ISSUE THREAD

**Issue by wudi1940** [sohutv/mqcloud#23]
目前的mqcloud支持管理多个集群，但对于某个topic来说，通过mqcloud创建相同命名的topic只能创建在一个集群上，而通过命令行创建的同名topic无法区分；这导致多环境的mq集群需要配置多环境的mqcloud；为什么不考虑给topic也打上集群的标签，来管理多集群的同名topic呢？

**Comment by gaoyf** [comment]
1. 底层集群对于用户是透明的，用户无需关心集群的信息，这个是设计的初衷。
2. 另外，全局唯一的topic对于用户申请时并不增加难度，因为topic根据组名+业务命名，可以做到全局唯一。

**Comment by wudi1940** [comment]
thanks for your reply
