### ISSUE TITLE
新建broker页面报错

### ISSUE THREAD

**Issue by leo432097** [sohutv/mqcloud#43]
你好， 在使用mqcloud 4.9.3 war包，在页面创建新的broker，点击一键部署无响应，F12查看为页面报错
![1681895245044](https://user-images.githubusercontent.com/18698586/233026409-e0850dd4-622d-45df-ba1d-36d61d02368d.png)
![1681895278250](https://user-images.githubusercontent.com/18698586/233027254-d48cb012-e163-48f5-bf3e-3e8b37670950.png)

**Comment by gaoyf** [comment]
可以使用master分支，此问题已经修复
