### ISSUE TITLE
topicID大于1000时被当做参数时因为是字符串会导致参数出现java字符串的逗号

### ISSUE THREAD

**Issue by MrCxin** [sohutv/mqcloud#44]
![image](https://github.com/sohutv/mqcloud/assets/18465320/9c0c89d4-a56f-4199-a2e8-48dfdb59cd3e)
![image](https://github.com/sohutv/mqcloud/assets/18465320/23410db1-24e1-4c12-8572-68ee00c2e43c)

**Comment by gaoyf** [comment]
用的版本发一下，目前master分支的代码应该没有这个问题。

**Comment by MrCxin** [comment]
3q
