### ISSUE TITLE
SSH 客户端太老旧了导致无法连接 Ubuntu22.04

### ISSUE THREAD

**Issue by liuweiGL** [sohutv/mqcloud#49]
项目中依赖的类库感觉升级一下比较好

**Comment by gaoyf** [comment]
请尝试如下方案：
1. 修改`/etc/ssh/sshd_config`，添加如下内容：

   ```
   HostKeyAlgorithms +ssh-rsa
   PubkeyAcceptedKeyTypes +ssh-rsa
   ```
3. 重启sshd，`sudo systemctl restart sshd`

**Comment by gaoyf** [comment]
[5.1.0.RELEASE](https://github.com/sohutv/mqcloud/releases/tag/5.1.0.RELEASE) 升级了SSH客户端，已经支持Ubuntu 22.04及一下版本了，可以试用一下。

**Comment by liuweiGL** [comment]
👍
