### ISSUE TITLE
Support what version about RokcetMQ

### ISSUE THREAD

**Issue by xiejiashuai** [sohutv/mqcloud#5]
Hello 
- I want to ask  what version can it support about RokcetMQ ?
- Will you open source this project along and  can support some help when used occur some problem ?

**Comment by gaoyf** [comment]
1 支持版本请参考：[6.其他说明](https://github.com/sohutv/mqcloud/wiki/6.其他说明)
2 是的，但是更愿意使用者能够自己研究源码，衍生出自己的需求，反馈或贡献给MQCloud。
