### ISSUE TITLE
Don't have default value

### ISSUE THREAD

**Issue by dlhf** [sohutv/mqcloud#7]
INSERT INTO `common_config`(`key`, `comment`) VALUES ('privateKey', '私钥');
INSERT INTO `common_config`(`key`, `comment`) VALUES ('adminAccessKey', '管理员访问名(broker&nameserver使用)');
INSERT INTO `common_config`(`key`, `comment`) VALUES ('adminSecretKey', '管理员访问私钥(broker&nameserver使用)');

**Comment by gaoyf** [comment]
你可以先执行下这个`alter table `common_config` modify column `value` varchar(20000) DEFAULT '' COMMENT '配置值';`
后续发版会加上这个，感谢反馈
